services:
  backend:
    image: shampiniony/mts-backend:latest
    restart: unless-stopped
    ports:
      - 8000:8000

  frontend:
    image: shampiniony/mts-frontend:latest
    restart: unless-stopped
    ports:
      - 3000:80