apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    image:
      name: traefik
      tag: 2.11.10
    ports:
      web:
        exposedPort: 80
        entryPoint: web
      websecure:
        exposedPort: 443
        entryPoint: websecure
    ingressRoute:
      enabled: true
    additionalArguments:
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email={{ .Values.global.email }}"
      - "--certificatesresolvers.le.acme.storage=/data/acme.json"
      - "--certificatesresolvers.le.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"  
    persistence:
      enabled: true
      size: 100m
      accessMode: ReadWriteOnce
      mountPath: /data
