namespace: mts

global:
  email: team@shamps.dev

backend:
  name: backend
  host: api.mts.shamps.dev
  port: 8000
  image:
    repository: shampiniony/mts-backend
    tag: 0.1.3
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
